# Line 1: The `name` attribute provides useful organizational information 
# when returning warnings, errors, and output. 
#The name should be meaningful to you as an action within your build process.
name: hello-world
# Line 2: The `on` is the name of the GitHub event that triggers the workflow.
on: push
# Line 3: The `jobs` level contains a collection of jobs that make up the workflow.
jobs:
  # Line 4-5: The `my-job` is an example of the name for a job, 
  # `runs-on` describes on which operating system the pipeline should run.
  my-job:
    runs-on: ubuntu-latest
    # Line 6-8: The `steps` collection is an ordered list of `run` directives. 
    # Each `run` directive is executed in the order in which it is declared.
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2 
      - name: my-step
        run: ci/build-app.sh
      - name: test
        run: ci/unit-test-app.sh
